name: fornetps_test_tech
description: "A new Mories project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  flutter_bloc: ^8.0.0
  get_it: ^8.0.0
  chucker_flutter: ^1.7.2
  dartz: ^0.10.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - variable_app.env
